// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASr9Mp4VFSzFVAbDnuj_mAsrcX_oAI8jw',
    appId: '1:248661822187:web:2adae8db5f046db7c08cae',
    messagingSenderId: '248661822187',
    projectId: 'gffft-auth',
    authDomain: 'gffft-auth.firebaseapp.com',
    databaseURL: 'https://gffft-auth.firebaseio.com',
    storageBucket: 'gffft-auth.appspot.com',
    measurementId: 'G-L1SR3JZ65R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChnlufnbxBnvX2PvEcnmS7P18f1yBL9NM',
    appId: '1:248661822187:android:09493f0b05269192c08cae',
    messagingSenderId: '248661822187',
    projectId: 'gffft-auth',
    databaseURL: 'https://gffft-auth.firebaseio.com',
    storageBucket: 'gffft-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgC6VlzqlijqkaHMRp7owdfvJ3avt6fQo',
    appId: '1:248661822187:ios:3f208fa31828ccfac08cae',
    messagingSenderId: '248661822187',
    projectId: 'gffft-auth',
    databaseURL: 'https://gffft-auth.firebaseio.com',
    storageBucket: 'gffft-auth.appspot.com',
    androidClientId: '248661822187-ocsfb0tn4jutid487uao3v7l5pdhli1a.apps.googleusercontent.com',
    iosClientId: '248661822187-17bbqptm8rqd8osai57aurdocnjs7frs.apps.googleusercontent.com',
    iosBundleId: 'com.approachingpi.gffft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgC6VlzqlijqkaHMRp7owdfvJ3avt6fQo',
    appId: '1:248661822187:ios:3f208fa31828ccfac08cae',
    messagingSenderId: '248661822187',
    projectId: 'gffft-auth',
    databaseURL: 'https://gffft-auth.firebaseio.com',
    storageBucket: 'gffft-auth.appspot.com',
    androidClientId: '248661822187-ocsfb0tn4jutid487uao3v7l5pdhli1a.apps.googleusercontent.com',
    iosClientId: '248661822187-17bbqptm8rqd8osai57aurdocnjs7frs.apps.googleusercontent.com',
    iosBundleId: 'com.approachingpi.gffft',
  );
}
